using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

include(joinpath(@__DIR__, "..", "src", "poison_nk_filter.jl"))

using MacroModelling
using Printf
using DataFrames
using CSV
using LinearAlgebra
using Random

println("=" ^ 76)
println("Tier-1 / Tier-2 analyses per RAND review")
println("=" ^ 76)

_ = get_irf(PoisonNK_Filter, periods = 1)   # pre-compile

##############################################################
# 1. Analytical MMSE Kalman gain benchmark
##############################################################
println("\n" * "=" ^ 76)
println("1. Analytical MMSE Kalman gain benchmark")
println("=" ^ 76)

# Simplified univariate signal-extraction: Fed observes
#   s_t = g_t + e_t
# where g_t ~ AR(1)(ρ_g, σ²_g,shock) is the true gap and
# e_t = ν_t + attack_t is the combined noise. For an AR(1) signal
# with serially-correlated observation noise, the standard
# approach is to augment the state. Here we use a simplified
# benchmark: treat g_t as AR(1) and observation noise as the
# unconditional variance of ν + attack.
#
# Steady-state Kalman for x_t = ρ·x_{t-1} + w_t,  y_t = x_t + v_t:
#   P = ρ²·(1 - K)·P + σ²_w       (Lyapunov/Riccati)
#   K = P / (P + σ²_v)
# Solving quadratic in P gives the MMSE gain K*.

function ss_kalman_gain(ρ, σ_w2, σ_v2)
    # Solve the Riccati: P satisfies
    #   P = ρ² · σ_v² · P / (P + σ_v²) + σ_w²
    # ⇒ P² + P·(σ_v²(1 - ρ²) - σ_w²) - σ_w²·σ_v² = 0
    a = 1.0
    b = σ_v2 * (1 - ρ^2) - σ_w2
    c = -σ_w2 * σ_v2
    P = (-b + sqrt(b^2 - 4a*c)) / (2a)
    K = P / (P + σ_v2)
    return (K = K, P = P)
end

# Parameters from our calibration
σ_r  = 0.4;  ρ_r   = 0.8
σ_ν  = 0.3;  ρ_ν   = 0.6
σ_a  = 1.0;  ρ_att = 0.8
ρ_p  = 0.85

# Unconditional variance of AR(1) shock: σ²/(1 - ρ²)
var_ν    = σ_ν^2 / (1 - ρ_ν^2)
var_att  = σ_a^2 / (1 - ρ_att^2)
var_noise_combined = var_ν + var_att

# The "true gap" is generated by the full NK structure; its unconditional
# variance depends on all shocks and policy. Use a rough benchmark:
# assume the gap's persistence matches ρ_p and its forecast-error variance
# is driven by the natural-rate shock passed through the IS curve.
# Under κ=0.15, SW-posterior, we can approximate var(ygap_forecast_error)
# by σ_r² (natural rate shock enters IS linearly with φ=1).
σ_gap_shock2 = σ_r^2    # rough, but order-of-magnitude correct

# MMSE gain under "attack active"
benchmark_attack = ss_kalman_gain(ρ_p, σ_gap_shock2, var_noise_combined)
# MMSE gain under "no attack" (σ_att=0, so observation noise is just ν)
benchmark_no_att = ss_kalman_gain(ρ_p, σ_gap_shock2, var_ν)

@printf("Signal variance (gap innovation):     %.4f\n", σ_gap_shock2)
@printf("Noise variance (ν only):              %.4f\n", var_ν)
@printf("Noise variance (ν + attack):          %.4f\n", var_noise_combined)
@printf("\nMMSE Kalman gain, no attack:          K* = %.4f\n", benchmark_no_att.K)
@printf("MMSE Kalman gain, attack active:      K* = %.4f\n", benchmark_attack.K)
println("\nOur swept optimum at empirical κ=0.15:  K_opt ≈ 0.025 (see run_filter_robustness.jl)")

##############################################################
# 2. λ sensitivity sweep
##############################################################
println("\n" * "=" ^ 76)
println("2. λ sensitivity sweep (welfare weight on gap variance)")
println("=" ^ 76)

function shock_variance_contribution(model, shk, var; params, periods=80, scale=1.0)
    irf = get_irf(model, parameters = params, periods = periods)
    series = [irf(var, p, shk) * scale for p in 1:periods]
    return sum(series .^ 2)
end

function welfare_loss(model; params, attack_on::Bool, λ=0.5, periods=80)
    σ_att_val = attack_on ? 1.0 : 0.0
    full_params = vcat(params, [:σ_att => σ_att_val])
    var_pi = sum(shock_variance_contribution(model, shk, :π;
                    params=full_params, periods=periods, scale=4.0)
                 for shk in [:ε_rn, :ε_ν, :ε_att])
    var_ygap = sum(shock_variance_contribution(model, shk, :ygap;
                    params=full_params, periods=periods)
                   for shk in [:ε_rn, :ε_ν, :ε_att])
    return (loss = var_pi + λ * var_ygap, var_pi = var_pi, var_ygap = var_ygap)
end

function crossover_threshold(model, κ_val::Float64, λ_val::Float64)
    base = [:κ => κ_val, :χ_p => 0.5, :h => 0.7, :ρ_i => 0.7, :ρ_p => 0.85]
    ks = 0.0:0.025:1.0
    L_off = Float64[]
    L_on  = Float64[]
    for K in ks
        params = vcat(base, [:K_gain => K])
        push!(L_off, welfare_loss(model, params=params, attack_on=false, λ=λ_val).loss)
        push!(L_on,  welfare_loss(model, params=params, attack_on=true,  λ=λ_val).loss)
    end
    idx_naive = findfirst(==(1.0), collect(ks))
    idx_best  = argmin(L_on)
    A = L_on[idx_naive];  C = L_off[idx_naive]
    B = L_on[idx_best];   D = L_off[idx_best]
    p_star = (D - C) / ((A - B) + (D - C))
    return (κ=κ_val, λ=λ_val, K_opt=ks[idx_best],
            p_crossover=p_star, L_on_naive=A, L_on_opt=B)
end

λ_values     = [0.1, 0.25, 0.5, 1.0]
κ_values     = [0.06, 0.15, 0.20]
lambda_rows  = DataFrame(κ=Float64[], λ=Float64[], K_opt=Float64[],
                          p_crossover=Float64[], L_on_naive=Float64[],
                          L_on_opt=Float64[])

println("\n     κ  |    λ  |  K_opt  | p*      | L_on(naive) | L_on(opt)")
println("-" ^ 72)
for κ in κ_values, λ in λ_values
    r = crossover_threshold(PoisonNK_Filter, κ, λ)
    @printf("  %.2f | %.2f | %6.3f | %6.2f%% | %11.3f | %9.3f\n",
            r.κ, r.λ, r.K_opt, 100*r.p_crossover, r.L_on_naive, r.L_on_opt)
    push!(lambda_rows, (r.κ, r.λ, r.K_opt, r.p_crossover, r.L_on_naive, r.L_on_opt))
end

CSV.write(joinpath(@__DIR__, "..", "results", "lambda_sensitivity.csv"), lambda_rows)

##############################################################
# 3. κ cost/benefit decomposition
##############################################################
println("\n" * "=" ^ 76)
println("3. κ cost/benefit decomposition")
println("=" ^ 76)

# At each κ, decompose welfare loss into var(π) and var(ygap) contributions
# Under naive (K=1) and optimal (K≈0.025), with attack on and off.

function decomposed_welfare(κ_val)
    base = [:κ => κ_val, :χ_p => 0.5, :h => 0.7, :ρ_i => 0.7, :ρ_p => 0.85]
    # Find K_opt at λ=0.5 for this κ
    ks = 0.0:0.025:1.0
    L_on_vec = Float64[]
    for K in ks
        p = vcat(base, [:K_gain => K])
        push!(L_on_vec, welfare_loss(PoisonNK_Filter, params=p, attack_on=true, λ=0.5).loss)
    end
    K_opt = ks[argmin(L_on_vec)]

    results = []
    for (regime_name, K_val) in [("naive", 1.0), ("optimal", K_opt)]
        for attack_on in [false, true]
            p = vcat(base, [:K_gain => K_val])
            w = welfare_loss(PoisonNK_Filter, params=p, attack_on=attack_on, λ=0.5)
            push!(results, (κ=κ_val, regime=regime_name, K_val=K_val,
                            attack_on=attack_on,
                            var_pi=w.var_pi, var_ygap=w.var_ygap, total=w.loss))
        end
    end
    return results, K_opt
end

decomp_rows = DataFrame(κ=Float64[], regime=String[], K_val=Float64[],
                         attack_on=Bool[], var_pi=Float64[],
                         var_ygap=Float64[], total=Float64[])

println("\n       κ  | regime  | K       | attack | var(π)    | var(ygap) | total")
println("-" ^ 82)
for κ in κ_values
    results, K_opt = decomposed_welfare(κ)
    for r in results
        @printf("    %.2f | %-7s | %.3f   | %-6s | %9.4f | %9.4f | %7.4f\n",
                r.κ, r.regime, r.K_val, string(r.attack_on),
                r.var_pi, r.var_ygap, r.total)
        push!(decomp_rows, (r.κ, r.regime, r.K_val, r.attack_on,
                            r.var_pi, r.var_ygap, r.total))
    end
end

CSV.write(joinpath(@__DIR__, "..", "results", "kappa_decomposition.csv"), decomp_rows)

##############################################################
# 4. Stochastic simulation standard errors on welfare
##############################################################
println("\n" * "=" ^ 76)
println("4. Stochastic simulation SEs on welfare (800-period paths, 50 draws)")
println("=" ^ 76)

# MacroModelling has get_simulation; use it to draw from the model
# and compute empirical variances.

function stoch_welfare_se(model; params, n_draws=50, n_periods=800, λ=0.5, burn=200)
    # get_simulation returns a KeyedArray (Variables × Periods × Shocks);
    # the Shocks dimension decomposes each var's path into per-shock contributions.
    # For the total simulated path we sum across shocks.
    losses = Float64[]
    for draw in 1:n_draws
        Random.seed!(1000 + draw)
        sim = get_simulation(model, parameters = params, periods = n_periods)
        # MacroModelling get_simulation returns a 3-axis KeyedArray
        # (Variables × Periods × Shocks) where the third axis has a single
        # entry :simulate — the combined realized path, not per-shock
        # decomposition. Extract the full path and drop burn-in.
        pi_path   = collect(sim(:π,    :, :simulate))
        ygap_path = collect(sim(:ygap, :, :simulate))
        pi_tail   = pi_path[(burn+1):end] .* 4.0   # annualized pp
        ygap_tail = ygap_path[(burn+1):end]
        var_pi   = sum(x^2 for x in pi_tail)   / length(pi_tail)
        var_ygap = sum(x^2 for x in ygap_tail) / length(ygap_tail)
        push!(losses, var_pi + λ * var_ygap)
    end
    m = sum(losses) / length(losses)
    return (mean = m,
            se = sqrt(sum((l - m)^2 for l in losses) /
                      (length(losses) * (length(losses) - 1))),
            n = length(losses))
end

println("\n  κ  |   K  | attack | mean L  |    SE   | n_draws")
println("-" ^ 62)

stoch_rows = DataFrame(κ=Float64[], K_gain=Float64[], attack_on=Bool[],
                        mean_L=Float64[], se_L=Float64[], n=Int[])

# Just do κ=0.15 (empirical), 4 key cells: naive/optimal × attack/no-attack
for (K_label, K_val) in [("naive", 1.0), ("optimal", 0.025)],
    attack_on in [false, true]

    σ_att_val = attack_on ? 1.0 : 0.0
    params = [:κ => 0.15, :χ_p => 0.5, :h => 0.7, :ρ_i => 0.7,
              :ρ_p => 0.85, :K_gain => K_val, :σ_att => σ_att_val]
    r = stoch_welfare_se(PoisonNK_Filter, params=params)
    @printf(" 0.15 | %.3f | %-6s | %7.3f | %7.3f | %d\n",
            K_val, string(attack_on), r.mean, r.se, r.n)
    push!(stoch_rows, (0.15, K_val, attack_on, r.mean, r.se, r.n))
end

CSV.write(joinpath(@__DIR__, "..", "results", "stochastic_ses.csv"), stoch_rows)

##############################################################
# 5. Alternative attacker objectives
##############################################################
println("\n" * "=" ^ 76)
println("5. Alternative attacker objectives (robustness)")
println("=" ^ 76)

# Three objectives:
#   (a) cumulative |Δi| (original: push rates down)
#   (b) inflation variance damage (maximize var(π))
#   (c) output-gap variance damage (maximize var(ygap))

γ_d = -log(0.5) / 0.8     # same calibration

function attacker_payoff_multi(model; A, ρ, K_gain, λ=0.5, periods=80)
    A_safe = max(A, 1e-6)
    ρ_safe = clamp(ρ, 0.0, 0.99)
    p_det = 1 - exp(-γ_d * A_safe^2 * ρ_safe)

    base = [:κ => 0.15, :χ_p => 0.5, :h => 0.7, :ρ_i => 0.7, :ρ_p => 0.85]
    params = vcat(base, [:σ_att => A_safe, :ρ_att => ρ_safe, :K_gain => K_gain])
    irf = get_irf(model, parameters = params, periods = periods)

    # (a) cumulative |Δi|: attacker wants rates down
    cum_i = -sum(irf(:i, p, :ε_att) * 100 for p in 1:8)

    # (b) var(π) damage (sum of squared IRFs attributable to attack shock)
    var_pi_attack = sum((irf(:π, p, :ε_att) * 4)^2 for p in 1:periods)

    # (c) var(ygap) damage
    var_ygap_attack = sum(irf(:ygap, p, :ε_att)^2 for p in 1:periods)

    return (p_det = p_det,
            payoff_a = (1 - p_det) * cum_i,
            payoff_b = (1 - p_det) * var_pi_attack,
            payoff_c = (1 - p_det) * var_ygap_attack)
end

A_grid = 0.1:0.2:3.0     # coarser than before
ρ_grid = 0.0:0.10:0.95

println("\nOptimal (A*, ρ*) by objective and Fed regime:")
println("-" ^ 80)
println("Regime       | Objective                | A*    | ρ*    | E[payoff]")
println("-" ^ 80)

attacker_rows = DataFrame(regime=String[], objective=String[],
                           A_star=Float64[], ρ_star=Float64[],
                           expected_utility=Float64[])

for (regime_name, K_val) in [("naive (K=1.0)", 1.0), ("filter (K=0.025)", 0.025)]
    best_a = (-Inf, 0.0, 0.0)
    best_b = (-Inf, 0.0, 0.0)
    best_c = (-Inf, 0.0, 0.0)
    for A in A_grid, ρ in ρ_grid
        r = attacker_payoff_multi(PoisonNK_Filter, A=A, ρ=ρ, K_gain=K_val)
        if r.payoff_a > best_a[1]; best_a = (r.payoff_a, A, ρ); end
        if r.payoff_b > best_b[1]; best_b = (r.payoff_b, A, ρ); end
        if r.payoff_c > best_c[1]; best_c = (r.payoff_c, A, ρ); end
    end
    for (obj_label, best) in [("(a) cumulative |Δi|", best_a),
                               ("(b) var(π) damage",  best_b),
                               ("(c) var(ygap) damage", best_c)]
        @printf("%-12s | %-24s | %.2f  | %.2f  | %.3f\n",
                regime_name, obj_label, best[2], best[3], best[1])
        push!(attacker_rows, (regime_name, obj_label, best[2], best[3], best[1]))
    end
    println()
end

CSV.write(joinpath(@__DIR__, "..", "results", "attacker_alt_objectives.csv"), attacker_rows)

println("\nDone. All Tier-1/2 CSVs written to results/.")
